### ISSUE TITLE
Wrap openapi in graphql gateway using https://the-guild.dev/graphql/mesh or similar

### ISSUE THREAD

**Issue by bebbi** [bebbi/ccdh-api-x#1]
The tasks are to
1) Add a graphql wrapper such as [this](https://the-guild.dev/graphql/mesh) to this package that will forward graphql queries from the front-end to the actual rest endpoint described in the openapi
2) Try an actual query, starting from the example in `app/page.tsx` (see comments there)
3) Discuss options to mock the rest api so we can play with the query without having access to the real endpoint.

**Comment by amaster507** [comment]
> Discuss options to mock the rest api so we can play with the query without having access to the real endpoint.

We can use api pages within this next app to mock up rest endpoints. Do we need to mockup the whole REST API or just enough for now to cover the example GraphQL query?

**Comment by bebbi** [comment]
Yes, mocking the entities of that query would be sufficient: `master_account`, `basic_account`, `card` for now.
