### ISSUE TITLE
Missing oid in Master Schema Definition

### ISSUE THREAD

**Issue by amaster507** [bebbi/ccdh-api-x#2]
There is a REST api route to get a `master` by the `oid` such as:

`https://<api.endpoint>/master/{oid}`

https://github.com/bebbi/ccdh-api-x/blob/2e4f5db739a7d85e69793d4f647e3e843873ae0a/openapi-x.json#L5387-L5940

I would assume this `oid` would map to unique identifier field on the `master` in the schema:

https://github.com/bebbi/ccdh-api-x/blob/2e4f5db739a7d85e69793d4f647e3e843873ae0a/openapi-x.json#L660-L873

But there does not appear to be a unique `oid` field in the `master` object in the OpenAPI schema definition file.

Is this a mistake, or does the API really not return the oid when requesting the master? If the later is true, then I will add a unique id in my data mock up and just not return the value of it.

But with GraphQL, it is important and I would say almost a hard requirement that every object returns some sort of unique identifier or at least a unique composite key.

If the current RESTful API does not expose this master oid, is it safe to expose it anyways?

**Comment by amaster507** [comment]
Similiar to this same issue:

Is `basic.accont_id` the equivalent of the `/basic/{oid}`

There is no `card.oid` equivalence for the route `/card/{oid}`

There is no `memo.oid` equivalence for the route `/memo/{oid}`

There is no `organization.oid` equivalence for the route `/organization/{oid}`

There is no `person.oid` equivalence for the route `/person/{oid}`

There is no `tag.oid` equivalence for the route `/tag/{oid}`

For `user` is the unique identifier a composite key of `name`+`email`? That seems to be a general consensus of foreign key relations in the other RESTful routes schemas.
See:

https://github.com/bebbi/ccdh-api-x/blob/main/openapi-x.json#L1479

and many other references of the same.

**Comment by bebbi** [comment]
Thanks! I've previously asked about oids missing in types, will follow up and try to make it a hard requirement. I think users need an oid. I'm not sure but your linked line could refer to audit trail type data which may need an original email (at the time of change), rather than a live connection back to a user objecr. I will also double-check this.
