### ISSUE TITLE
Unstructured JSON response in OpenAPI definitions

### ISSUE THREAD

**Issue by amaster507** [bebbi/ccdh-api-x#3]
The following routes:

- [/basic](https://github.com/bebbi/ccdh-api-x/blob/main/openapi-x.json#L1589)
- [/card](https://github.com/bebbi/ccdh-api-x/blob/main/openapi-x.json#L2303)
- [/country](https://github.com/bebbi/ccdh-api-x/blob/main/openapi-x.json#L3385)
- [/currency](https://github.com/bebbi/ccdh-api-x/blob/main/openapi-x.json#L4020)
- [/master](https://github.com/bebbi/ccdh-api-x/blob/main/openapi-x.json#L4544)
- [/memo](https://github.com/bebbi/ccdh-api-x/blob/main/openapi-x.json#L5466)
- [/organization](https://github.com/bebbi/ccdh-api-x/blob/main/openapi-x.json#L6020)
- [/person](https://github.com/bebbi/ccdh-api-x/blob/main/openapi-x.json#L6479)
- [/tag](https://github.com/bebbi/ccdh-api-x/blob/main/openapi-x.json#L8235)
- [/user](https://github.com/bebbi/ccdh-api-x/blob/main/openapi-x.json#L8635)

are all schemad to return an array of `application/json` instead of the correctly schemad type.

This is causing issues when adding graphql-mesh because the types are left as JSON strings in the GraphQL response instead of structured out into the actual types.

**Comment by bebbi** [comment]
Is it possible that you write one example line for what one fixed entity return looks like?And I will forward it with the request for fixing it.

**Comment by amaster507** [comment]
Here is the fix of just one of these.

f20306b

And this generates the corrected GraphQL pattern.

![image](https://user-images.githubusercontent.com/2472115/206890401-86ca15f5-1805-465e-8e7c-5f85bd8a2080.png)

[Ignore the naming conventions for now, I will overwrite these generated query names]
